[service]
host_interface = 0.0.0.0
service_port = 8000

[database]
# postgres
type = mysql
host = localhost
port = 3306
name = your_db_name
username = your_db_user
password = your_db_password

[logging]
filename = /tmp/soap_sync_client.log
filemode = a
format = %(asctime)s,%(msecs)d pid:%(process)d %(name)s %(levelname)s %(message)s
dateformat = %H:%M:%S
# info warning debug
level = INFO
